spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?serverTimezone=GMT%2b8
    username:
    password:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

pagehelper:
  reasonable: true
  support-methods-arguments: true

file:
  uploadFolder: E:/毕业论文/code/springboot/src/main/resources/static/img/
